// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: address-service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AddressRegistrationClient is the client API for AddressRegistration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AddressRegistrationClient interface {
	RegisterAddress(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*AddressResponse, error)
}

type addressRegistrationClient struct {
	cc grpc.ClientConnInterface
}

func NewAddressRegistrationClient(cc grpc.ClientConnInterface) AddressRegistrationClient {
	return &addressRegistrationClient{cc}
}

func (c *addressRegistrationClient) RegisterAddress(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*AddressResponse, error) {
	out := new(AddressResponse)
	err := c.cc.Invoke(ctx, "/proto.AddressRegistration/RegisterAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddressRegistrationServer is the server API for AddressRegistration service.
// All implementations must embed UnimplementedAddressRegistrationServer
// for forward compatibility
type AddressRegistrationServer interface {
	RegisterAddress(context.Context, *AddressRequest) (*AddressResponse, error)
	mustEmbedUnimplementedAddressRegistrationServer()
}

// UnimplementedAddressRegistrationServer must be embedded to have forward compatible implementations.
type UnimplementedAddressRegistrationServer struct {
}

func (UnimplementedAddressRegistrationServer) RegisterAddress(context.Context, *AddressRequest) (*AddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAddress not implemented")
}
func (UnimplementedAddressRegistrationServer) mustEmbedUnimplementedAddressRegistrationServer() {}

// UnsafeAddressRegistrationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddressRegistrationServer will
// result in compilation errors.
type UnsafeAddressRegistrationServer interface {
	mustEmbedUnimplementedAddressRegistrationServer()
}

func RegisterAddressRegistrationServer(s grpc.ServiceRegistrar, srv AddressRegistrationServer) {
	s.RegisterService(&AddressRegistration_ServiceDesc, srv)
}

func _AddressRegistration_RegisterAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressRegistrationServer).RegisterAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddressRegistration/RegisterAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressRegistrationServer).RegisterAddress(ctx, req.(*AddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AddressRegistration_ServiceDesc is the grpc.ServiceDesc for AddressRegistration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AddressRegistration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AddressRegistration",
	HandlerType: (*AddressRegistrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAddress",
			Handler:    _AddressRegistration_RegisterAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "address-service.proto",
}
